version: "3.5"

services:
  db:
    image: mysql:5.7
    container_name: task_full_db
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_app
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskdb
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/db/schema.sql
    ports:
      - "3306:3306"